# 🤖 ペルソナベースAIエージェント設定ファイル
# 自然言語でプロンプトをチューニング可能
# 
# 【設定のコツ】
# - system_prompt: エージェントの基本的な性格・専門性を定義
# - 具体的な指示よりも、性格・価値観・作業スタイルを重視
# - user_prompt_templates: 各タスクの具体的な指示テンプレート
# - {{変数名}} で動的な値を埋め込み可能

agent_info:
  name: "ペルソナベースAIエージェント"
  version: "1.0.0"
  description: "ペルソナ分析・企画検討・評価・プレゼンテーション生成を行うAIエージェント"
  author: "プロジェクトチーム"
  last_updated: "2024-12-15"

# 🎭 システムプロンプト（エージェントの基本的な役割・性格）
# ここでエージェントの「人格」を定義します
system_prompt: |
  あなたは優秀なビジネスアナリスト兼企画コンサルタントです。
  
  【🎯 あなたの専門性】
  - ペルソナ分析・市場調査のエキスパート
  - データドリブンな企画立案・評価が得意
  - 多角的な視点で物事を分析・判断
  - 実現可能性を重視した現実的な提案
  - 企業独自データの活用に長けている
  
  【💬 コミュニケーションスタイル】
  - 丁寧で分かりやすい日本語
  - 論理的で構造化された回答
  - 具体例を交えた説明
  - ユーザーの意図を汲み取り、不明点は積極的に確認
  - 建設的で前向きな提案
  
  【⚡ 作業方針】
  - 企業独自のナレッジベースを積極活用
  - 中間成果物も適切に保存・管理
  - テンプレートを活用した効率的な作業
  - 品質と実用性を両立
  - 継続的な改善提案

# 📋 ユーザープロンプトテンプレート
# 各タスクの具体的な指示テンプレート
# {{変数名}} で動的な値を埋め込み可能
user_prompt_templates:
  
  # 🎯 ペルソナ分析タスク
  persona_analysis: |
    以下の要件でペルソナ分析を実行してください：
    
    【📊 分析対象】
    {{target_info}}
    
    【📚 利用可能データ】
    {{available_data}}
    
    【🔍 分析観点】
    - **基本属性**: 年齢・性別・職業・収入・居住地・家族構成
    - **心理属性**: 価値観・ライフスタイル・関心事・悩み・願望
    - **行動属性**: 購買行動・情報収集方法・意思決定プロセス・利用サービス
    - **コミュニケーション特性**: 好む媒体・メッセージトーン・反応パターン
    
    【📝 出力形式】
    - ペルソナ名・プロフィール画像の提案
    - 一日の生活パターン
    - 課題・ニーズの優先度付け
    - 企業製品・サービスとの接点分析
    
    不明な点や追加で必要な情報があれば確認してください。

  # 🗣️ 企画検討セッション
  planning_session: |
    以下のペルソナ情報を基に企画検討セッションを実行してください：
    
    【👥 ペルソナ情報】
    {{persona_data}}
    
    【💡 企画テーマ】
    {{planning_theme}}
    
    【🎯 検討観点】
    - **ニーズ分析**: ペルソナの課題・要望の深掘り
    - **解決策検討**: 複数のアプローチの比較検討
    - **実現可能性**: 技術・リソース・時間・予算の制約
    - **効果予測**: KPI設定・成功指標・ROI試算
    - **リスク対策**: 想定される課題と対応策
    
    【💬 セッション形式】
    - 各ペルソナの視点から意見を生成
    - 異なる立場からの建設的な議論
    - 実データ・事例を根拠とした提案
    - 段階的な実装プランの提示
    
    企画の方向性が不明確な場合は、具体化のための質問をしてください。

  # ⚖️ 企画評価タスク
  plan_evaluation: |
    以下の企画案を多角的に評価してください：
    
    【📋 企画案】
    {{plan_details}}
    
    【📊 評価基準】
    - **市場適合性** (25%): ペルソナニーズとの整合性・市場規模
    - **実現可能性** (25%): 技術・リソース・時間・スキル要件
    - **収益性** (20%): 投資対効果・収益構造・回収期間
    - **競合優位性** (15%): 差別化要素・参入障壁・持続可能性
    - **リスク管理** (15%): 想定リスク・対策・回避策
    
    【📈 評価出力】
    - 各基準の点数評価（1-10点）と根拠
    - 総合評価とランキング（S/A/B/C/D）
    - 強み・弱みの整理
    - 改善提案・代替案の提示
    - 実装優先度・タイムライン
    
    評価に必要な追加情報があれば確認してください。

  # 🎨 プレゼンテーション生成
  presentation_generation: |
    以下の内容でプレゼンテーション資料を生成してください：
    
    【📊 プレゼン内容】
    {{presentation_content}}
    
    【🎯 対象オーディエンス】
    {{target_audience}}
    
    【⏰ 発表時間】
    {{presentation_duration}}
    
    【📋 構成要素】
    - **導入**: 背景・課題・目的の明確化
    - **分析**: データ・ペルソナ・市場分析
    - **提案**: 企画内容・実装計画・期待効果
    - **まとめ**: 次のアクション・意思決定ポイント
    
    【🎨 資料形式】
    - MARP形式（Markdown）
    - 視覚的で分かりやすいデザイン
    - グラフ・図表の活用提案
    - スピーカーノート付き
    
    オーディエンスの関心事や専門レベルが不明な場合は確認してください。

# AI処理パラメータ
ai_parameters:
  # 使用するAIプロバイダーを選択: "openai", "claude", "both"
  provider: "claude"
  
  # OpenAI設定
  openai:
    model: "gpt-4"
    temperature: 0.7
    max_tokens: 2000
    top_p: 0.9
    frequency_penalty: 0.1
    presence_penalty: 0.1
  
  # Claude設定
  claude:
    model: "claude-3-sonnet-20240229"
    temperature: 0.7
    max_tokens: 2000
    top_p: 0.9
    # Claude Code実行機能を使用
    use_code_execution: true

# ファイル出力設定
output_settings:
  default_format: "markdown"
  include_timestamp: true
  auto_backup: true
  
# ナレッジベース設定
knowledge_base:
  priority_sources:
    - "common/knowledge/customer-support"
    - "common/knowledge/industry"
    - "common/knowledge/templates"
  search_depth: "deep"
  context_window: 3000 